app:
  scheduler:
    enable: true
    interval: 5000
    unusedLinksInterval: 86400000
    force-check-delay: 10s
  database-access-type: jdbc

spring:
  liquibase:
    enabled: false
  config:
    import: optional:file:.env[.properties]
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8080


api:
  bot:
    baseurl: http://localhost:8090
    retryPolicy: linear
  stackoverflow:
    baseurl: https://api.stackexchange.com/2.3/
    retryPolicy: linear
  github:
    retryPolicy: linear
    baseurl: https://api.github.com/
    token: ${GITHUB_TOKEN}

springdoc:
  swagger-ui:
    path: /swagger-ui

