app:
  scheduler:
    enable: true
    interval: 5000
    unusedLinksInterval: 86400000
    force-check-delay: 10s
  database-access-type: jdbc
  useQueue: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topicName: botUpdates

spring:
  liquibase:
    enabled: false
  config:
    import: optional:file:.env[.properties]
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 8080


api:
  bot:
    baseurl: http://localhost:8090
    retryPolicy: linear
    retryCount: 5
    linearArg: 2
    codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  stackoverflow:
    baseurl: https://api.stackexchange.com/2.3/
    retryPolicy: linear
    retryCount: 4
    linearArg: 4
    codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  github:
    retryPolicy: linear
    baseurl: https://api.github.com/
    token: ${GITHUB_TOKEN}
    retryCount: 3
    linearArg: 4
    codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  queryCount: 30
