app:
  scheduler:
    enable: true
    interval: 5000
    force-check-delay: 10s

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  bot:
    baseurl: http://localhost:8090
  stackoverflow:
    baseurl: https://api.stackexchange.com/2.3/
  github:
    baseurl: https://api.github.com/
    token: ${GITHUB_TOKEN}

springdoc:
  swagger-ui:
    path: /swagger-ui

