app:
  telegram-token: ${TELEGRAM_TOKEN}


spring:
  main:
    allow-circular-references: true
  config:
    import: optional:file:.env[.properties]
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false

server:
  port: 8090


api:
  scrapper:
    baseurl: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui
