app:
  telegram-token: ${TELEGRAM_TOKEN}


spring:
  main:
    allow-circular-references: true
  config:
    import: optional:file:.env[.properties]
  application:
    name: bot
  jackson:
    time-zone: UTC
  liquibase:
    enabled: false

server:
  port: 8090


api:
  scrapper:
    baseurl: http://localhost:8080
    retryPolicy: linear
    constantRetry: 3
    linearRetry: 4
    exponentialRetry: 5
    linearArg: 3


springdoc:
  swagger-ui:
    path: /swagger-ui
