/*
 * This file is generated by jOOQ.
 */

package edu.java.repository.jooq.tables.pojos;


import jakarta.validation.constraints.Size;
import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String url;
    private OffsetDateTime updateAt;
    private OffsetDateTime lastApiUpdate;

    public Link() {}

    public Link(Link value) {
        this.id = value.id;
        this.url = value.url;
        this.updateAt = value.updateAt;
        this.lastApiUpdate = value.lastApiUpdate;
    }

    @ConstructorProperties({ "id", "url", "updateAt", "lastApiUpdate" })
    public Link(
        @Nullable Long id,
        @NotNull String url,
        @Nullable OffsetDateTime updateAt,
        @Nullable OffsetDateTime lastApiUpdate
    ) {
        this.id = id;
        this.url = url;
        this.updateAt = updateAt;
        this.lastApiUpdate = lastApiUpdate;
    }

    /**
     * Getter for <code>LINK.ID</code>.
     */
    @Nullable
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>LINK.ID</code>.
     */
    public void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>LINK.URL</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 255)
    @NotNull
    public String getUrl() {
        return this.url;
    }

    /**
     * Setter for <code>LINK.URL</code>.
     */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    /**
     * Getter for <code>LINK.UPDATE_AT</code>.
     */
    @Nullable
    public OffsetDateTime getUpdateAt() {
        return this.updateAt;
    }

    /**
     * Setter for <code>LINK.UPDATE_AT</code>.
     */
    public void setUpdateAt(@Nullable OffsetDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * Getter for <code>LINK.LAST_API_UPDATE</code>.
     */
    @Nullable
    public OffsetDateTime getLastApiUpdate() {
        return this.lastApiUpdate;
    }

    /**
     * Setter for <code>LINK.LAST_API_UPDATE</code>.
     */
    public void setLastApiUpdate(@Nullable OffsetDateTime lastApiUpdate) {
        this.lastApiUpdate = lastApiUpdate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Link other = (Link) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.url == null) {
            if (other.url != null)
                return false;
        }
        else if (!this.url.equals(other.url))
            return false;
        if (this.updateAt == null) {
            if (other.updateAt != null)
                return false;
        }
        else if (!this.updateAt.equals(other.updateAt))
            return false;
        if (this.lastApiUpdate == null) {
            if (other.lastApiUpdate != null)
                return false;
        }
        else if (!this.lastApiUpdate.equals(other.lastApiUpdate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.url == null) ? 0 : this.url.hashCode());
        result = prime * result + ((this.updateAt == null) ? 0 : this.updateAt.hashCode());
        result = prime * result + ((this.lastApiUpdate == null) ? 0 : this.lastApiUpdate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Link (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(updateAt);
        sb.append(", ").append(lastApiUpdate);

        sb.append(")");
        return sb.toString();
    }
}
